# Tint16 generated palette
# Theme: "{name}"
# Author: "{author}"

[colors]
ansi = [
    '{color0}',
    '{color1}',
    '{color2}',
    '{color3}',
    '{color4}',
    '{color5}',
    '{color6}',
    '{color7}',
]
brights = [
    '{color8}',
    '{color9}',
    '{color10}',
    '{color11}',
    '{color12}',
    '{color13}',
    '{color14}',
    '{color15}',
]
cursor_border = '{color15}'
cursor_bg = '{color0}'
cursor_fg = '{color8}'
background = '{background}'
foreground = '{foreground}'
selection_bg = '{color8}'
selection_fg = '{foreground}'

[colors.indexed]

[metadata]
name = 'Wezterm'
