# Tint16 generated palette
# Theme: "basoa-summer"
# Author: "Itzalak"

[colors]
ansi = [
    '#353f0e',
    '#e14433',
    '#5cb200',
    '#ebbe2f',
    '#56b8f7',
    '#bd97fc',
    '#27c3d9',
    '#b9d64a',
]
brights = [
    '#637321',
    '#f36552',
    '#6aca00',
    '#fbd66e',
    '#89cdfc',
    '#ceb5fd',
    '#42daf1',
    '#f3fbdf',
]
cursor_border = '#f3fbdf'
cursor_bg = '#353f0e'
cursor_fg = '#637321'
background = '#092a13'
foreground = '#e2f6a6'
selection_bg = '#637321'
selection_fg = '#e2f6a6'

[colors.indexed]

[metadata]
name = 'Wezterm'
